### ISSUE TITLE
Unexpected method call sub() for a DateTime object

### ISSUE THREAD

**Issue by rodrigodiez** [phpspec/phpspec#887] opened 2016-03-15 15:27 UTC
We are experiencing an issue with `\DateTime` mocks.

Whenever we mock a `\DateTime` object and set an spy that checks for that `\DateTime` object to be passed as argument in a call to a collaborator, we get an unexpected call to that DateTime's `sub` method

Error:

```
11  - it should call bObject with provided datetime
    method call:
      - sub(DateInterval:00000000701b8e350000557477af2bd5 Object (
        'y' => 0
        'm' => 0
        'd' => 0
        'h' => 0
        'i' => 0
        's' => 0
        'weekday' => 0
        'weekday_behavior' => 0
        'first_last_day_of' => 0
        'invert' => 0
        'days' => false
        'special_type' => 0
        'special_amount' => 0
        'have_weekday_relative' => 0
        'have_special_relative' => 0
    ))
    on Double\DateTime\P1 was not expected, expected calls were:
      - getTimestamp()

```

Please find attached a full example, you can also clone it from [it's own repository](https://github.com/rodrigodiez/phpspec-datetime-issue)

``` php
<?php

namespace ACME;

use ACME\ClassB;

class ClassA
{
    public function foo(ClassB $bObject, \DateTime $datetime)
    {
        return $bObject->bar($datetime);
    }
}
```

``` php
<?php

namespace ACME;

class ClassB
{
    public function bar(\DateTime $datetime) {

    }
}
```

``` php
<?php

namespace spec\ACME;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;
use ACME\ClassB;

class ClassASpec extends ObjectBehavior
{
    function it_should_call_bObject_with_provided_datetime(ClassB $bObject, \DateTime $datetime)
    {
        // commenting out this line solves the issue
        $datetime->getTimestamp()->willReturn(1458054681);

        $bObject->bar($datetime)->shouldBeCalled();

        $this->foo($bObject, $datetime);
    }
}
```

**Comment by jakzal** [comment] 2016-03-16 08:52
Why are you mocking `\DateTime`? Just create an instance.

**Comment by rodrigodiez** [comment] 2016-03-16 15:33
That sounds like a workaround. Can't I mock \DateTime objects with prophecy?

**Comment by sroze** [comment] 2016-03-16 15:44
You can mock `DateTime` objects, you'll simply have to explicitly set the result of each method call. 

*But* we don't consider it as a really good practice for many reasons, including the fact that for instance, if your implementation is not using the `getDate` method anymore but `getTimestamp` at some point, you'll need to change all your tests to match this. Your `DateTime` object is a Value Object (except that it it mutable... :(), so you shouldn't even need to mock it, but simply give an instance.

**Comment by jakzal** [comment] 2016-03-16 15:45
It's not a workaround. I treat DateTime more as a value object. Besides, don't mock what you don't own :)

**Comment by stof** [comment] 2016-03-16 15:46
The issue is that the PHPUnit comparison library is used when matching arguments, and it does such ``sub`` calls when handling DateTime objects: https://github.com/sebastianbergmann/comparator/blob/937efb279bd37a375bcadf584dec0726f84dbf22/src/DateTimeComparator.php#L46

Prophecy should register a comparator able of comparing its doubles without performing extra calls on them, to avoid running the comparison logic aimed at the real object (which does not make sense for such case). Please open an issue on Prophecy about that.

However, I agree with @sroze and @jakzal that using a real instance is perfectly acceptable here, and probably even better than mocking it.

**Comment by stof** [comment] 2016-03-16 15:48
btw, the fix may even be requested in the Comparator library, as PHPUnit uses Prophecy. PHPunit_Mock_Object is supported directly in the library for instance.

**Comment by sebastianbergmann** [comment] 2018-07-12 13:17
IMO, there is no need to stub/mock value objects such as `DateTimeImmutable`. But that is besides the point here.

The point is that if you stub/mock `DateTimeImmutable` then you need to configure its methods. I understand that it may be unexpected that the [DateTimeComparator](https://github.com/sebastianbergmann/comparator/blob/master/src/DateTimeComparator.php#L44) calls a method on a `DateTimeImmutable` object. But this is required for making the comparison of `DateTimeImmutable` objects work as expected.

**Comment by sebastianbergmann** [comment] 2018-07-12 15:29
The order in which the default comparators are tried was wrong. This has been fixed in https://github.com/sebastianbergmann/comparator/commit/2da53a8494af23b965a3c2fbcf98087ea53360f1 and apparently solves the problem when test doubles created using PHPUnit's `createMock()` etc. are used.

Maybe Prophecy needs its own custom comparator?

**Closed** 2019-08-05 12:15 UTC
Labels: bug
