### ISSUE TITLE
Using PHPSpec with Doctrine QueryBuilder

### ISSUE THREAD

**Issue by Maelstromeous** [phpspec/phpspec#1222] opened 2018-08-21 17:35 UTC
Hi all,

I'm attempting to try and test a class which contains a Doctrine QueryBuilder. I realise that yes, you shouldn't be mocking a class that you don't own, however how can the class itself run without it?

[Here's a stackoverflow ](https://stackoverflow.com/questions/51953430/how-do-i-handle-doctrine-querybuilder-within-phpspec)explaining the situation and the code, figured I'd DRY and link to it there.

I'm fairly new to PHPSpec tests, so a concept could have whooshed over me. All I'm after is to be able to test the response of the query, not necessarily everything that Doctrine does in that context. When omitting the tests however the concrete class is failing as it doesn't know what to do with Doctrine, so I'm stuck.

Please help!

**Comment by nightlinus** [comment] 2018-08-22 19:35
Phpspec in this context is wrong tool, write integration test with phpunit or any other general-purpose test framework.

**Comment by ddziaduch** [comment] 2018-08-27 19:57
You can use PhpSpec to do integration tests using https://github.com/BossaConsulting/phpspec2-expect ;)

**Comment by jakzal** [comment] 2018-11-07 09:56
> I'm attempting to try and test a class which contains a Doctrine QueryBuilder. I realise that yes, you shouldn't be mocking a class that you don't own, however how can the class itself run without it?

Make sure that the class that uses the query builder is only a small integration layer between your code and doctrine (i.e. hide it behind a repository interface, gateway etc).
Write an integration test for this layer. Phpspec won't help here, but you can use phpunit.
Anywhere else you'll now be able to stub/mock your class/interface without having to directly depend on the query builder (this is dependency inversion in practice).

> I'm fairly new to PHPSpec tests, so a concept could have whooshed over me. All I'm after is to be able to test the response of the query, not necessarily everything that Doctrine does in that context. 

The best test for this is the one that calls the database. Otherwise the test is worthless. It's easy to make a typo in `$qb->from('Usre', 'u')->willReturn($qb)` and repeat the same typo in test. The test will pass, but what is it validating really?

> When omitting the tests however the concrete class is failing as it doesn't know what to do with Doctrine, so I'm stuck.

Not sure what you mean by this.

**Comment by ciaranmcnulty** [comment] 2019-08-05 12:05
I'm going to close this because I'm not sure where the conversation went. If you have a more reproducible case please re-open

**Closed by ciaranmcnulty** 2019-08-05 12:05 UTC
