### ISSUE TITLE
[php 7.2] incompatible prototype

### ISSUE THREAD

**Issue by remicollet** [phpspec/phpspec#1094] opened 2017-05-12 08:14 UTC
Running test suite against 7.2.0-dev which have more strict checking:

`
PHP Fatal error:  Declaration of Double\PhpSpec\Console\ConsoleIO\P83::write($message) must be compatible with PhpSpec\Console\ConsoleIO::write($message, $indent = NULL, $newline = false) in /usr/share/php/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2
`

Yes, quite early report.. ;)

**Comment by ciaranmcnulty** [comment] 2017-05-12 08:23
At first glance this would appear to be a PHP bug not a PhpSpec bug?

**Comment by ciaranmcnulty** [comment] 2017-05-12 08:24
(In that PHP isn't supposed to break BC)

**Comment by ciaranmcnulty** [comment] 2017-05-12 08:25
(will probably still fix it ;-) )

**Comment by remicollet** [comment] 2017-05-12 08:29
> At first glance this would appear to be a PHP bug not a PhpSpec bug?

Prototype are really different, PHP 7.2 is simply stricter.
(IIRC this have been apply, then reverted in 7.1 to be strictly BC compliant)

**Comment by ciaranmcnulty** [comment] 2017-05-12 08:30
This also seems to be a Prophecy bug? I'll see if I can reproduce

**Comment by Sam-Burns** [comment] 2017-05-12 08:31
So is it PhpSpec or Prophecy that this would need to be fixed in?

**Comment by ciaranmcnulty** [comment] 2017-06-02 13:11
Finally fixed in #1108

**Closed by ciaranmcnulty** 2017-06-02 13:11 UTC
