### ISSUE TITLE
[FR] Add warning about mismatch namespaces or empty test files

### ISSUE THREAD

**Issue by xorik** [phpspec/phpspec#1143] opened 2017-08-28 07:44 UTC
Hi.

Sometimes when I change service's namespace, I move the file inside the `spec` folder, but forget to change the namespace. So tests inside this file aren't running.

It would be great, if I can see some warning message for these files. If it's hard to implement, maybe it's easy to show some warnings for php files without tests inside (like we have for empty methods)?

**Comment by meridius** [comment] 2018-03-15 08:31
This is duplicate of older #354

**Comment by jakzal** [comment] 2018-03-15 10:09
@meridius thanks for spotting it! Closing as a duplicate of #354.

**Closed by jakzal** 2018-03-15 10:09 UTC
Labels: feature
