### ISSUE TITLE
Error running tests when pass scalar type argument

### ISSUE THREAD

**Issue by krystianzybala** [phpspec/phpspec#834] opened 2016-01-03 09:06 UTC
PHP 7.0
PHSpec 2.4.1

I trying to handle exceptions PHP7 in PHPSpec  but PHPSpec return Fatal Error  instead catch Exception. 
Code :
```php
<?php
declare(strict_types=1);
namespace Test;

class Example
{
 
    public function test(string $name)
    {
        $this->name = $name;
    }
}
?>

<?php
declare(strict_types=1);
namespace spec\Test;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class ExampleSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType('Test\Example');
    }

    function it_check_test_method_when_not_pass_argument()
    {
        $this->shouldThrow('\TypeError')->during('test');
    }
}
?>
```
Info Error : 
Uncaught TypeError: Argument 1 passed to Test\Example::test()  must be of the type integer, none given, none given in /home/projects/test/Test/Example.php

How can I handle TypeError in PHPSpec? 
Is this a known issue?

**Comment by jakzal** [comment] 2016-01-03 09:22
You did not pass any arguments to your method call. 

This:

    $this->shouldThrow('\TypeError')->during('test');

is equivalent to:

    $this->shouldThrow('\TypeError')->duringTest();

"test" is a method name, not an argument.

You should either use:

    $this->shouldThrow('\TypeError')->during('test', [new \stdClass()]);

or:

    $this->shouldThrow('\TypeError')->duringTest(new \stdClass());

However, I see no value in this kind of tests, as they're more about testing php (type system) then your code.

**Comment by jakzal** [comment] 2016-01-03 09:24
Nevertheless, phpspec should probably handle this kind of errors.

**Comment by ciaranmcnulty** [comment] 2016-01-03 09:27
This is a duplicate of #769 , please continue discussion there

**Closed by ciaranmcnulty** 2016-01-03 09:27 UTC
