### ISSUE TITLE
check marks in pretty formatter are not shown correctly in windows

### ISSUE THREAD

**Issue by mohamadnorouzi20** [phpspec/phpspec#821] opened 2015-12-13 17:20 UTC
![capture](https://cloud.githubusercontent.com/assets/8435784/11768224/d0dac5fc-a1bd-11e5-9b53-c1265429b8df.jpg)

**Comment by ciaranmcnulty** [comment] 2015-12-13 17:29
This is a duplicate of #106

**Closed by ciaranmcnulty** 2015-12-13 17:29 UTC
